#--------------------- PORT Server ------------------
server:
  port: 8081
#--------------------- Filer Settings ------------------
spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  http:
    multipart:
      enabled: false
#--------------------JPA-ORM Properties-----------------
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#--------------------- DB Connection ------------------
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bfo_signature_v1.0
    username: postgres
    password: admin
#--------------------- Keycloak Server ---------------
keycloak:
  realm: Sistema de Firmas Digitales
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: Sistema de Firmas Digitales -BFO
  public-client: false
#--------------------- Path Folders ------------------
path-out-zip: C:\\Users\\jyujra\\Desktop\\ServerFile-BFO\\ZIP_OUT
dir-pdf-firma: C:\\Users\\jyujra\\Desktop\\ServerFile-BFO\\PDF_FIRMADOS
path-out-zip-home: C:\\Users\\jyujra\\Desktop\\ServerFile-BFO\\PDF_ZIP
#--------------------- Splits Server ------------------
path-system: \\