#--------------------- PORT Server ------------------
server:
  port: 8081
#--------------------- Filer Settings ------------------
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  http:
    multipart:
      enabled: false
#--------------------JPA-ORM Properties-----------------
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#--------------------- DB Connection ------------------
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://10.17.8.78:5432/signature}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
#--------------------- Path Folders ------------------
path-out-zip: /opt/files/ZIP_OUT
dir-pdf-firma: /opt/files/PDF_FIRMADOS
path-out-zip-home: /opt/files/PDF_ZIP
#--------------------- Splits Server ------------------
path-system: /
